# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 我的博客 #网站标题
subtitle: 又一个GoodHexo小站 #网站副标题
description: 基于GoodHexo便携包搭建的博客，官方网站：http://sobaigu.com #网站描述
keywords: #网站SEO关键词
author: http://sobaigu.com  #网站作者
timezone: Asia/Shanghai
# language: en
language: zh-Hans #theme: yelee，next
#language: zh-CN  #theme: maupassant，landscape

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: yelee
#theme: maupassant
theme: next

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://xuehuaduoduo.github.io
root: /
#permalink: :year/:month/:day/:title/
permalink: :title.html  #链接发布格式
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:title.md # MarkDown源文件组织格式
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
# 设置首页分页之前默认就有，这里就不额外加了
# index_generator:
#   per_page: 5
archive_generator:
  per_page: 40  #值为0表示不分页，按需填写
  yearly: true  #是否按年生成归档
  monthly: false  #为了加快生成速度，按月归档就不要了
tag_generator:
  per_page: 40  #值为0表示不分页，按需填写
category_generator:
  per_page: 40  #值为0表示不分页，按需填写

# 生成sitemap
sitemap:
    path: sitemap.xml
    tag: false
    category: false
    
# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: 'git'
  repo: git@github.com:xuehuaduoduo/xuehuaduoduo.github.io.git
  branch: master
  message: Hexo update

# backup
backup:
  type: git
  message: Hexo backup
  repository: 
    github: git@github.com:xuehuaduoduo/xuehuaduoduo.github.io.git,backup2

symbols_count_time:
  symbols: true                # 文章字数统计
  time: true                   # 文章阅读时长
  total_symbols: true          # 站点总字数统计
  total_time: true             # 站点总阅读时长
  exclude_codeblock: false     # 排除代码字数统计
  